sonar.projectKey=cybersapienseci_profile-service
sonar.organization=cybersapienseci
sonar.projectName=AlphaECI Profile Service

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

# Exclude generated/boilerplate code from analysis
sonar.exclusions=\
  **/*.spec.ts,\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**

# Exclude infrastructure and entrypoints from coverage (hard to unit-test)
sonar.coverage.exclusions=\
  **/dto/**,\
  **/main.ts,\
  **/infrastructure/**,\
  **/entrypoints/**

sonar.cpd.exclusions=**/dto/**
