sonar.projectKey=cybersapienseci_profile-service
sonar.organization=cybersapienseci
sonar.projectName=AlphaECI Profile Service

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

sonar.exclusions=\
  **/*.spec.ts,\
  **/*.e2e-spec.ts,\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**

sonar.coverage.exclusions=\
  **/dto/**,\
  **/main.ts,\
  **/*.module.ts,\
  **/infrastructure/**,\
  **/entrypoints/**,\
  **/service/**,\
  src/health/**,\
  **/exceptions/external-service.exception.ts,\
  **/exceptions/image-profile.exception.ts,\
  **/exceptions/user-already-exists.exception.ts,\
  **/exceptions/user-not-found.exception.ts,\
  **/exceptions/index.ts,\
  **/ports/in/index.ts,\
  **/*.d.ts

sonar.cpd.exclusions=**/dto/**
