export enum CareerEnum {
  // Ingenierías
  SYSTEMS_ENGINEERING = 'SYSTEMS_ENGINEERING',
  CIVIL_ENGINEERING = 'CIVIL_ENGINEERING',
  INDUSTRIAL_ENGINEERING = 'INDUSTRIAL_ENGINEERING',
  ELECTRONIC_ENGINEERING = 'ELECTRONIC_ENGINEERING',
  ELECTRICAL_ENGINEERING = 'ELECTRICAL_ENGINEERING',
  MECHANICAL_ENGINEERING = 'MECHANICAL_ENGINEERING',
  BIOMEDICAL_ENGINEERING = 'BIOMEDICAL_ENGINEERING',
  ENVIRONMENTAL_ENGINEERING = 'ENVIRONMENTAL_ENGINEERING',
  STATISTICAL_ENGINEERING = 'STATISTICAL_ENGINEERING',
  BIOTECHNOLOGY_ENGINEERING = 'BIOTECHNOLOGY_ENGINEERING',
  ARTIFICIAL_INTELLIGENCE_ENGINEERING = 'ARTIFICIAL_INTELLIGENCE_ENGINEERING',
  CYBERSECURITY_ENGINEERING = 'CYBERSECURITY_ENGINEERING',

  // Ciencias y tecnología
  COMPUTER_SCIENCE = 'COMPUTER_SCIENCE',
  MATHEMATICS = 'MATHEMATICS',
  DATA_SCIENCE = 'DATA_SCIENCE',

  // Negocios y economía
  BUSINESS_ADMINISTRATION = 'BUSINESS_ADMINISTRATION',
  ECONOMICS = 'ECONOMICS',

  // Tecnología
  INFORMATION_TECHNOLOGY = 'INFORMATION_TECHNOLOGY',
}
